<#
𓂀  Codex CGL Orchestrator v1.2 — Plan-Only Preview Node
    Generated by CGL v1.2 compiler.

Role:
  • Load CGL state JSON (v1.2).
  • Read execution_plan.
  • Print planned routing steps (no external engines yet).
  • Future versions: expand into full All-One orchestrators.

Law:
  Anchor → Load → Inspect → Reflect → Return
#>

param(
    [string]$StatePath,
    [string]$Mode = "plan"
)

$ErrorActionPreference = "Stop"

if ([string]::IsNullOrWhiteSpace($StatePath)) {
    Write-Host "[CGL v1.2 Orchestrator] ✖ No -StatePath provided."
    return
}

if (-not (Test-Path "$StatePath")) {
    Write-Host "[CGL v1.2 Orchestrator] ✖ State file not found: $StatePath"
    return
}

$stateJson = Get-Content "$StatePath" -Raw
$state     = $stateJson | ConvertFrom-Json

$plan = $state.program.execution_plan
if ($plan -eq $null) {
    Write-Host "[CGL v1.2 Orchestrator] ✖ No execution_plan in state."
    return
}

Write-Host "[CGL v1.2 Orchestrator] Loaded execution_plan with $($plan.Count) steps."
Write-Host "[CGL v1.2 Orchestrator] Mode=$Mode (v1.2 is plan/preview only)."
Write-Host ""

foreach ($step in $plan) {
    Write-Host ("[step {0} | block {1}] glyph={2} opcode={3} channel={4} role={5}" -f `
        $step.step_index, $step.block_index, $step.glyph, $step.opcode, $step.channel, $step.role)
}

Write-Host ""
Write-Host "[CGL v1.2 Orchestrator] Compilation target reached (preview)."
Write-Host "[CGL v1.2 Orchestrator] Future versions will emit full All-One workflows per opcode."
